language: c

script: ./autogen.sh && ./configure --enable-tests --enable-threads && make && make check && make distclean && sudo apt-get update -qq && sudo apt-get install -qq check libopenmpi-dev openmpi-bin && ./configure --enable-tests && make && make check
 

compiler:
  - clang
  - gcc

notifications:
  email:
    - jonb@lanl.gov
