language: c

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq check

script: ./configure --enable-threads --enable-tests && make && make test

compiler:
  - clang
  - gcc

notifications:
  email:
    - jonb@lanl.gov
